repos:
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: bash -c 'source backend/venv/bin/activate && pytest'
        language: system
        types: [python]
        pass_filenames: false
        always_run: true 