services:
  # Backend service
  - type: web
    name: counselai-backend-v2
    runtime: python
    plan: starter # Plan payant - $7/mois
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: GEMINI_API_KEY
        sync: false # You'll set this in Render dashboard
      - key: PYTHON_VERSION
        value: 3.11

  # Frontend service  
  - type: web
    name: counselai-frontend-v2
    runtime: static
    plan: free
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18